version: '3'
services:
  fastify-api:
    build: .
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
    # env_file:
    #   - ./.env
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - ./.env
    volumes:
      - fastify_volume:/var/lib/postgres/data

volumes:
  fastify_volume: {}
